/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  aux_sym_comment_token1 = 3,
  anon_sym_SLASH_STAR = 4,
  aux_sym_block_comment_token1 = 5,
  anon_sym_SLASH = 6,
  anon_sym_DQUOTE = 7,
  aux_sym_string_token1 = 8,
  anon_sym_SQUOTE = 9,
  aux_sym_string_token2 = 10,
  aux_sym_number_token1 = 11,
  aux_sym_number_token2 = 12,
  aux_sym_number_token3 = 13,
  anon_sym_if = 14,
  anon_sym_else = 15,
  anon_sym_while = 16,
  anon_sym_loop = 17,
  anon_sym_for = 18,
  anon_sym_return = 19,
  anon_sym_break = 20,
  anon_sym_continue = 21,
  anon_sym_goto = 22,
  anon_sym_gosub = 23,
  anon_sym_class = 24,
  anon_sym_extends = 25,
  anon_sym_global = 26,
  anon_sym_local = 27,
  anon_sym_static = 28,
  anon_sym_try = 29,
  anon_sym_catch = 30,
  anon_sym_finally = 31,
  anon_sym_throw = 32,
  anon_sym_new = 33,
  anon_sym_true = 34,
  anon_sym_false = 35,
  anon_sym_and = 36,
  anon_sym_or = 37,
  anon_sym_not = 38,
  sym__operator = 39,
  sym_source_file = 40,
  sym__statement = 41,
  sym_comment = 42,
  sym_block_comment = 43,
  sym_string = 44,
  sym_number = 45,
  sym_keyword = 46,
  aux_sym_source_file_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_block_comment_token1] = "block_comment_token1",
  [anon_sym_SLASH] = "/",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_loop] = "loop",
  [anon_sym_for] = "for",
  [anon_sym_return] = "return",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [anon_sym_goto] = "goto",
  [anon_sym_gosub] = "gosub",
  [anon_sym_class] = "class",
  [anon_sym_extends] = "extends",
  [anon_sym_global] = "global",
  [anon_sym_local] = "local",
  [anon_sym_static] = "static",
  [anon_sym_try] = "try",
  [anon_sym_catch] = "catch",
  [anon_sym_finally] = "finally",
  [anon_sym_throw] = "throw",
  [anon_sym_new] = "new",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_not] = "not",
  [sym__operator] = "_operator",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_comment] = "comment",
  [sym_block_comment] = "block_comment",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_keyword] = "keyword",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_block_comment_token1] = aux_sym_block_comment_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [anon_sym_goto] = anon_sym_goto,
  [anon_sym_gosub] = anon_sym_gosub,
  [anon_sym_class] = anon_sym_class,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_global] = anon_sym_global,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_static] = anon_sym_static,
  [anon_sym_try] = anon_sym_try,
  [anon_sym_catch] = anon_sym_catch,
  [anon_sym_finally] = anon_sym_finally,
  [anon_sym_throw] = anon_sym_throw,
  [anon_sym_new] = anon_sym_new,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_not] = anon_sym_not,
  [sym__operator] = sym__operator,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_comment] = sym_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_keyword] = sym_keyword,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_goto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gosub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_global] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_static] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_try] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_catch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_finally] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_throw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_new] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [sym__operator] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(13);
      if (lookahead == '\'') ADVANCE(16);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == '0') ADVANCE(21);
      if (lookahead == ';') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(13);
      if (lookahead == '\'') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '0') ADVANCE(21);
      if (lookahead == ':') ADVANCE(25);
      if (lookahead == ';') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('!' <= lookahead && lookahead <= '@') ||
          ('[' <= lookahead && lookahead <= '^') ||
          ('{' <= lookahead && lookahead <= '~')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          ('(' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          ('[' <= lookahead && lookahead <= '^') ||
          ('{' <= lookahead && lookahead <= '~')) ADVANCE(26);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(2);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (lookahead == '.') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__operator);
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          ('(' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          ('[' <= lookahead && lookahead <= '^') ||
          ('{' <= lookahead && lookahead <= '~')) ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__operator);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          ('(' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          ('[' <= lookahead && lookahead <= '^') ||
          ('{' <= lookahead && lookahead <= '~')) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__operator);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          ('(' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          ('[' <= lookahead && lookahead <= '^') ||
          ('{' <= lookahead && lookahead <= '~')) ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'e', 4,
        'f', 5,
        'g', 6,
        'i', 7,
        'l', 8,
        'n', 9,
        'o', 10,
        'r', 11,
        's', 12,
        't', 13,
        'w', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'l') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(20);
      if (lookahead == 'x') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(22);
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(34);
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(37);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(48);
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 28:
      if (lookahead == 'c') ADVANCE(50);
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 29:
      if (lookahead == 'w') ADVANCE(52);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(55);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(57);
      if (lookahead == 'y') ADVANCE(58);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 38:
      if (lookahead == 'a') ADVANCE(60);
      END_STATE();
    case 39:
      if (lookahead == 'c') ADVANCE(61);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 44:
      if (lookahead == 's') ADVANCE(66);
      END_STATE();
    case 45:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 47:
      if (lookahead == 'b') ADVANCE(68);
      END_STATE();
    case 48:
      if (lookahead == 'u') ADVANCE(69);
      END_STATE();
    case 49:
      if (lookahead == 'o') ADVANCE(70);
      END_STATE();
    case 50:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 51:
      if (lookahead == 'p') ADVANCE(72);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_new);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 54:
      if (lookahead == 'u') ADVANCE(73);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_try);
      END_STATE();
    case 59:
      if (lookahead == 'l') ADVANCE(77);
      END_STATE();
    case 60:
      if (lookahead == 'k') ADVANCE(78);
      END_STATE();
    case 61:
      if (lookahead == 'h') ADVANCE(79);
      END_STATE();
    case 62:
      if (lookahead == 's') ADVANCE(80);
      END_STATE();
    case 63:
      if (lookahead == 'i') ADVANCE(81);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 65:
      if (lookahead == 'n') ADVANCE(82);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 67:
      if (lookahead == 'l') ADVANCE(84);
      END_STATE();
    case 68:
      if (lookahead == 'a') ADVANCE(85);
      END_STATE();
    case 69:
      if (lookahead == 'b') ADVANCE(86);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_goto);
      END_STATE();
    case 71:
      if (lookahead == 'l') ADVANCE(87);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 73:
      if (lookahead == 'r') ADVANCE(88);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 75:
      if (lookahead == 'w') ADVANCE(90);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 77:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_catch);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 81:
      if (lookahead == 'n') ADVANCE(92);
      END_STATE();
    case 82:
      if (lookahead == 'd') ADVANCE(93);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 84:
      if (lookahead == 'l') ADVANCE(94);
      END_STATE();
    case 85:
      if (lookahead == 'l') ADVANCE(95);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_gosub);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 88:
      if (lookahead == 'n') ADVANCE(96);
      END_STATE();
    case 89:
      if (lookahead == 'c') ADVANCE(97);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_throw);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 92:
      if (lookahead == 'u') ADVANCE(98);
      END_STATE();
    case 93:
      if (lookahead == 's') ADVANCE(99);
      END_STATE();
    case 94:
      if (lookahead == 'y') ADVANCE(100);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_global);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_static);
      END_STATE();
    case 98:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_finally);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_number_token3] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_goto] = ACTIONS(1),
    [anon_sym_gosub] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_global] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_static] = ACTIONS(1),
    [anon_sym_try] = ACTIONS(1),
    [anon_sym_catch] = ACTIONS(1),
    [anon_sym_finally] = ACTIONS(1),
    [anon_sym_throw] = ACTIONS(1),
    [anon_sym_new] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(13),
    [sym__statement] = STATE(2),
    [sym_comment] = STATE(2),
    [sym_block_comment] = STATE(2),
    [sym_string] = STATE(2),
    [sym_number] = STATE(2),
    [sym_keyword] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_SLASH_STAR] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(15),
    [aux_sym_number_token3] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(19),
    [anon_sym_while] = ACTIONS(19),
    [anon_sym_loop] = ACTIONS(19),
    [anon_sym_for] = ACTIONS(19),
    [anon_sym_return] = ACTIONS(19),
    [anon_sym_break] = ACTIONS(19),
    [anon_sym_continue] = ACTIONS(19),
    [anon_sym_goto] = ACTIONS(19),
    [anon_sym_gosub] = ACTIONS(19),
    [anon_sym_class] = ACTIONS(19),
    [anon_sym_extends] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_static] = ACTIONS(19),
    [anon_sym_try] = ACTIONS(19),
    [anon_sym_catch] = ACTIONS(19),
    [anon_sym_finally] = ACTIONS(19),
    [anon_sym_throw] = ACTIONS(19),
    [anon_sym_new] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [anon_sym_and] = ACTIONS(19),
    [anon_sym_or] = ACTIONS(19),
    [anon_sym_not] = ACTIONS(19),
    [sym__operator] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(3),
    [sym_comment] = STATE(3),
    [sym_block_comment] = STATE(3),
    [sym_string] = STATE(3),
    [sym_number] = STATE(3),
    [sym_keyword] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_SLASH_STAR] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(15),
    [aux_sym_number_token3] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_else] = ACTIONS(19),
    [anon_sym_while] = ACTIONS(19),
    [anon_sym_loop] = ACTIONS(19),
    [anon_sym_for] = ACTIONS(19),
    [anon_sym_return] = ACTIONS(19),
    [anon_sym_break] = ACTIONS(19),
    [anon_sym_continue] = ACTIONS(19),
    [anon_sym_goto] = ACTIONS(19),
    [anon_sym_gosub] = ACTIONS(19),
    [anon_sym_class] = ACTIONS(19),
    [anon_sym_extends] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_static] = ACTIONS(19),
    [anon_sym_try] = ACTIONS(19),
    [anon_sym_catch] = ACTIONS(19),
    [anon_sym_finally] = ACTIONS(19),
    [anon_sym_throw] = ACTIONS(19),
    [anon_sym_new] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [anon_sym_and] = ACTIONS(19),
    [anon_sym_or] = ACTIONS(19),
    [anon_sym_not] = ACTIONS(19),
    [sym__operator] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym_comment] = STATE(3),
    [sym_block_comment] = STATE(3),
    [sym_string] = STATE(3),
    [sym_number] = STATE(3),
    [sym_keyword] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(30),
    [anon_sym_SLASH_STAR] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(36),
    [anon_sym_SQUOTE] = ACTIONS(39),
    [aux_sym_number_token1] = ACTIONS(42),
    [aux_sym_number_token2] = ACTIONS(42),
    [aux_sym_number_token3] = ACTIONS(45),
    [anon_sym_if] = ACTIONS(48),
    [anon_sym_else] = ACTIONS(48),
    [anon_sym_while] = ACTIONS(48),
    [anon_sym_loop] = ACTIONS(48),
    [anon_sym_for] = ACTIONS(48),
    [anon_sym_return] = ACTIONS(48),
    [anon_sym_break] = ACTIONS(48),
    [anon_sym_continue] = ACTIONS(48),
    [anon_sym_goto] = ACTIONS(48),
    [anon_sym_gosub] = ACTIONS(48),
    [anon_sym_class] = ACTIONS(48),
    [anon_sym_extends] = ACTIONS(48),
    [anon_sym_global] = ACTIONS(48),
    [anon_sym_local] = ACTIONS(48),
    [anon_sym_static] = ACTIONS(48),
    [anon_sym_try] = ACTIONS(48),
    [anon_sym_catch] = ACTIONS(48),
    [anon_sym_finally] = ACTIONS(48),
    [anon_sym_throw] = ACTIONS(48),
    [anon_sym_new] = ACTIONS(48),
    [anon_sym_true] = ACTIONS(48),
    [anon_sym_false] = ACTIONS(48),
    [anon_sym_and] = ACTIONS(48),
    [anon_sym_or] = ACTIONS(48),
    [anon_sym_not] = ACTIONS(48),
    [sym__operator] = ACTIONS(27),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_identifier] = ACTIONS(53),
    [anon_sym_SEMI] = ACTIONS(51),
    [anon_sym_SLASH_STAR] = ACTIONS(53),
    [anon_sym_DQUOTE] = ACTIONS(51),
    [anon_sym_SQUOTE] = ACTIONS(51),
    [aux_sym_number_token1] = ACTIONS(51),
    [aux_sym_number_token2] = ACTIONS(51),
    [aux_sym_number_token3] = ACTIONS(53),
    [anon_sym_if] = ACTIONS(53),
    [anon_sym_else] = ACTIONS(53),
    [anon_sym_while] = ACTIONS(53),
    [anon_sym_loop] = ACTIONS(53),
    [anon_sym_for] = ACTIONS(53),
    [anon_sym_return] = ACTIONS(53),
    [anon_sym_break] = ACTIONS(53),
    [anon_sym_continue] = ACTIONS(53),
    [anon_sym_goto] = ACTIONS(53),
    [anon_sym_gosub] = ACTIONS(53),
    [anon_sym_class] = ACTIONS(53),
    [anon_sym_extends] = ACTIONS(53),
    [anon_sym_global] = ACTIONS(53),
    [anon_sym_local] = ACTIONS(53),
    [anon_sym_static] = ACTIONS(53),
    [anon_sym_try] = ACTIONS(53),
    [anon_sym_catch] = ACTIONS(53),
    [anon_sym_finally] = ACTIONS(53),
    [anon_sym_throw] = ACTIONS(53),
    [anon_sym_new] = ACTIONS(53),
    [anon_sym_true] = ACTIONS(53),
    [anon_sym_false] = ACTIONS(53),
    [anon_sym_and] = ACTIONS(53),
    [anon_sym_or] = ACTIONS(53),
    [anon_sym_not] = ACTIONS(53),
    [sym__operator] = ACTIONS(53),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_identifier] = ACTIONS(57),
    [anon_sym_SEMI] = ACTIONS(55),
    [anon_sym_SLASH_STAR] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(55),
    [anon_sym_SQUOTE] = ACTIONS(55),
    [aux_sym_number_token1] = ACTIONS(55),
    [aux_sym_number_token2] = ACTIONS(55),
    [aux_sym_number_token3] = ACTIONS(57),
    [anon_sym_if] = ACTIONS(57),
    [anon_sym_else] = ACTIONS(57),
    [anon_sym_while] = ACTIONS(57),
    [anon_sym_loop] = ACTIONS(57),
    [anon_sym_for] = ACTIONS(57),
    [anon_sym_return] = ACTIONS(57),
    [anon_sym_break] = ACTIONS(57),
    [anon_sym_continue] = ACTIONS(57),
    [anon_sym_goto] = ACTIONS(57),
    [anon_sym_gosub] = ACTIONS(57),
    [anon_sym_class] = ACTIONS(57),
    [anon_sym_extends] = ACTIONS(57),
    [anon_sym_global] = ACTIONS(57),
    [anon_sym_local] = ACTIONS(57),
    [anon_sym_static] = ACTIONS(57),
    [anon_sym_try] = ACTIONS(57),
    [anon_sym_catch] = ACTIONS(57),
    [anon_sym_finally] = ACTIONS(57),
    [anon_sym_throw] = ACTIONS(57),
    [anon_sym_new] = ACTIONS(57),
    [anon_sym_true] = ACTIONS(57),
    [anon_sym_false] = ACTIONS(57),
    [anon_sym_and] = ACTIONS(57),
    [anon_sym_or] = ACTIONS(57),
    [anon_sym_not] = ACTIONS(57),
    [sym__operator] = ACTIONS(57),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_SEMI] = ACTIONS(59),
    [anon_sym_SLASH_STAR] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(59),
    [anon_sym_SQUOTE] = ACTIONS(59),
    [aux_sym_number_token1] = ACTIONS(59),
    [aux_sym_number_token2] = ACTIONS(59),
    [aux_sym_number_token3] = ACTIONS(61),
    [anon_sym_if] = ACTIONS(61),
    [anon_sym_else] = ACTIONS(61),
    [anon_sym_while] = ACTIONS(61),
    [anon_sym_loop] = ACTIONS(61),
    [anon_sym_for] = ACTIONS(61),
    [anon_sym_return] = ACTIONS(61),
    [anon_sym_break] = ACTIONS(61),
    [anon_sym_continue] = ACTIONS(61),
    [anon_sym_goto] = ACTIONS(61),
    [anon_sym_gosub] = ACTIONS(61),
    [anon_sym_class] = ACTIONS(61),
    [anon_sym_extends] = ACTIONS(61),
    [anon_sym_global] = ACTIONS(61),
    [anon_sym_local] = ACTIONS(61),
    [anon_sym_static] = ACTIONS(61),
    [anon_sym_try] = ACTIONS(61),
    [anon_sym_catch] = ACTIONS(61),
    [anon_sym_finally] = ACTIONS(61),
    [anon_sym_throw] = ACTIONS(61),
    [anon_sym_new] = ACTIONS(61),
    [anon_sym_true] = ACTIONS(61),
    [anon_sym_false] = ACTIONS(61),
    [anon_sym_and] = ACTIONS(61),
    [anon_sym_or] = ACTIONS(61),
    [anon_sym_not] = ACTIONS(61),
    [sym__operator] = ACTIONS(61),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym_identifier] = ACTIONS(65),
    [anon_sym_SEMI] = ACTIONS(63),
    [anon_sym_SLASH_STAR] = ACTIONS(65),
    [anon_sym_DQUOTE] = ACTIONS(63),
    [anon_sym_SQUOTE] = ACTIONS(63),
    [aux_sym_number_token1] = ACTIONS(63),
    [aux_sym_number_token2] = ACTIONS(63),
    [aux_sym_number_token3] = ACTIONS(65),
    [anon_sym_if] = ACTIONS(65),
    [anon_sym_else] = ACTIONS(65),
    [anon_sym_while] = ACTIONS(65),
    [anon_sym_loop] = ACTIONS(65),
    [anon_sym_for] = ACTIONS(65),
    [anon_sym_return] = ACTIONS(65),
    [anon_sym_break] = ACTIONS(65),
    [anon_sym_continue] = ACTIONS(65),
    [anon_sym_goto] = ACTIONS(65),
    [anon_sym_gosub] = ACTIONS(65),
    [anon_sym_class] = ACTIONS(65),
    [anon_sym_extends] = ACTIONS(65),
    [anon_sym_global] = ACTIONS(65),
    [anon_sym_local] = ACTIONS(65),
    [anon_sym_static] = ACTIONS(65),
    [anon_sym_try] = ACTIONS(65),
    [anon_sym_catch] = ACTIONS(65),
    [anon_sym_finally] = ACTIONS(65),
    [anon_sym_throw] = ACTIONS(65),
    [anon_sym_new] = ACTIONS(65),
    [anon_sym_true] = ACTIONS(65),
    [anon_sym_false] = ACTIONS(65),
    [anon_sym_and] = ACTIONS(65),
    [anon_sym_or] = ACTIONS(65),
    [anon_sym_not] = ACTIONS(65),
    [sym__operator] = ACTIONS(65),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(67),
    [sym_identifier] = ACTIONS(69),
    [anon_sym_SEMI] = ACTIONS(67),
    [anon_sym_SLASH_STAR] = ACTIONS(69),
    [anon_sym_DQUOTE] = ACTIONS(67),
    [anon_sym_SQUOTE] = ACTIONS(67),
    [aux_sym_number_token1] = ACTIONS(67),
    [aux_sym_number_token2] = ACTIONS(67),
    [aux_sym_number_token3] = ACTIONS(69),
    [anon_sym_if] = ACTIONS(69),
    [anon_sym_else] = ACTIONS(69),
    [anon_sym_while] = ACTIONS(69),
    [anon_sym_loop] = ACTIONS(69),
    [anon_sym_for] = ACTIONS(69),
    [anon_sym_return] = ACTIONS(69),
    [anon_sym_break] = ACTIONS(69),
    [anon_sym_continue] = ACTIONS(69),
    [anon_sym_goto] = ACTIONS(69),
    [anon_sym_gosub] = ACTIONS(69),
    [anon_sym_class] = ACTIONS(69),
    [anon_sym_extends] = ACTIONS(69),
    [anon_sym_global] = ACTIONS(69),
    [anon_sym_local] = ACTIONS(69),
    [anon_sym_static] = ACTIONS(69),
    [anon_sym_try] = ACTIONS(69),
    [anon_sym_catch] = ACTIONS(69),
    [anon_sym_finally] = ACTIONS(69),
    [anon_sym_throw] = ACTIONS(69),
    [anon_sym_new] = ACTIONS(69),
    [anon_sym_true] = ACTIONS(69),
    [anon_sym_false] = ACTIONS(69),
    [anon_sym_and] = ACTIONS(69),
    [anon_sym_or] = ACTIONS(69),
    [anon_sym_not] = ACTIONS(69),
    [sym__operator] = ACTIONS(69),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(71), 1,
      aux_sym_comment_token1,
  [4] = 1,
    ACTIONS(73), 1,
      aux_sym_block_comment_token1,
  [8] = 1,
    ACTIONS(75), 1,
      aux_sym_string_token1,
  [12] = 1,
    ACTIONS(77), 1,
      aux_sym_string_token2,
  [16] = 1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
  [20] = 1,
    ACTIONS(81), 1,
      anon_sym_SLASH,
  [24] = 1,
    ACTIONS(83), 1,
      anon_sym_DQUOTE,
  [28] = 1,
    ACTIONS(83), 1,
      anon_sym_SQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 4,
  [SMALL_STATE(11)] = 8,
  [SMALL_STATE(12)] = 12,
  [SMALL_STATE(13)] = 16,
  [SMALL_STATE(14)] = 20,
  [SMALL_STATE(15)] = 24,
  [SMALL_STATE(16)] = 28,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [79] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_autohotkey(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
